# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "csm-test-app"
client_id = "57b05e8e591238694aa634138ed61eba"
application_url = "https://messaging-ladies-texas-sticker.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://messaging-ladies-texas-sticker.trycloudflare.com/auth/callback",
  "https://messaging-ladies-texas-sticker.trycloudflare.com/auth/shopify/callback",
  "https://messaging-ladies-texas-sticker.trycloudflare.com/api/auth/callback",
  "https://messaging-ladies-texas-sticker.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "haseeb-group-development.myshopify.com"
